Step fifth
lenaswiss/aqa-java-course pull request #7
Opened 2023-04-12 15:31 UTC by lenaswiss

2023-04-20 10:51 UTC, NastiaRudia requested changes

2023-04-20 10:51 UTC, NastiaRudia commented on src/basicsyntax/Arrays.java
> +            System.out.println("AVG of array = " + sum / array.length);
додатково вигадані завдання перевіряти не буду більше, ці всі перевірки вже роблять в роботі з колекціями, так як з голим масови ніхто не працює, а з arraylist , array == null (раджу уникати таку перевірку в лоб на null, краще використовувати optional), якшо вже перевірила array == null , то для чого воно знову тут  else if (array.length == 0 || array == null) {

2023-04-20 10:51 UTC, NastiaRudia commented on src/basicsyntax/Arrays.java
> +            i++;
а чому i++ не тут for (int i = 0; i < a.length;  i++)

2023-04-21 20:13 UTC, lenaswiss commented on src/basicsyntax/Arrays.java
> +            System.out.println("AVG of array = " + sum / array.length);
Да все верно второй раз проверка на null не нужна, уберу.

2023-04-21 20:17 UTC, lenaswiss commented on src/basicsyntax/Arrays.java
> +            i++;
Исправила, спасибо.

2023-04-21 20:17 UTC, merged